### ISSUE TITLE
Commit 6d7a042 issue with messages formatted with minetest.colorize from clients

### ISSUE THREAD

**Issue by Baigle** [wsor4035/shadowmute#1]
Error "sorry, pinging discord users or roles is disallowed:nil" is shown when colorized message is sent from a 5.6.1 client.

https://github.com/wsor4035/shadowmute/commit/6d7a042e6362f6606a3a99d7778135f656e2653c

**Comment by wsor4035** [comment]
probably pattern matching the sequence for color. probably could just do `message = minetest.strip_colors(message)` and pattern match from there. personally i dislike color, so idc, but PR's accepted. that message comes from https://github.com/wsor4035/shadowmute/blob/master/modules/pingblock.lua#L7 so idk why your linking the latest commit
