### ISSUE TITLE
Command whitelist issue

### ISSUE THREAD

**Issue by zeminori** [wsor4035/shadowmute#3]
In the 13th string of modules/repeatblock.lua there is check if command registered. But, in 12th string, command-matching using :split()[1] function, that returning, for example `"/cmd"`. But minetest.registered_chatcommands storing chatcommands without `/`(slash). In this way, expression `if (minetest.registered_chatcommands[command]`, where `command` = `"/cmd"` will always return nil.
* How to fix:
The simpliest way is cutting `/` from `command` using `gsub`:
`if (minetest.registered_chatcommands[command:gsub("/","")]`

**Comment by wsor4035** [comment]
heh, your right, doesnt help when i did my check to see how minetest keyed the array, i did `//lua minetest.chat_send_all(dump(minetest.registered_chatcommands))` which showed some worldedit commands at the end

**Comment by wsor4035** [comment]
fyi, used `:sub` to strip the first character, because of worldedit commands
