### ISSUE TITLE
Server crashes after sending “space bar” just twice. on catlandia as well.

### ISSUE THREAD

**Issue by Bratwurst-Pomologist** [wsor4035/shadowmute#4]
Server crashes after sending “space bar” just twice in chat.

**Comment by wsor4035** [comment]
sending just space twice in a row, cant replicate

**Comment by wsor4035** [comment]
seems this server has a mod that changes how chat works, since normal minetest chat wont send a single space

**Comment by wsor4035** [comment]
interesting, older minetest *server* version such as minetest 5.4 aka muc2 will let you send a space to chat, while newer versions (5.8) will not

**Comment by wsor4035** [comment]
https://github.com/wsor4035/shadowmute/commit/2004274108ee34c71c370d1d24fb72b5a07388fd

**Comment by wsor4035** [comment]
updated the mod on the server btw

**Comment by Bratwurst-Pomologist** [comment]
bug is fixed. well done and thank you. :)
